### ISSUE TITLE
Error While Erasing Flash Memory

### ISSUE THREAD

**Issue by engineeredbyme** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#12]
Hello, I am still getting this error utilizing the fireware updater code+plugin. I am utilizing an Arduino Uno and the connection is working but there seems to be a memory problem and I have no idea how to solve it.

> 
> java.lang.Exception: Error while erasing flash memory.
> 	at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.eraseFlash(FlasherSerialClient.java:139)
> 	at cc.arduino.plugins.wifi101.flashers.java.JavaFlasher.updateFirmware(JavaFlasher.java:79)
> 	at cc.arduino.plugins.wifi101.UpdaterImpl$3.run(UpdaterImpl.java:138)
>

**Comment by facchinm** [comment]
Hi @engineeredbyme ,
the two latest firmwares released by Atmel (Microchip) only target the B revision of the WINC1500 chip, so unfortunately they can't be flashed on the WiFi101 shield. The latest firmware you can flash is 19.4.4.
