### ISSUE TITLE
Unable to update firmware WINC1500 19.5.4 or upload SSL certificates

### ISSUE THREAD

**Issue by antellus** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#14]
I've gone through the instructions a few times.  It seems like the board cannot be updated to 19.5.4.   Along with that, I am receiving errors trying to upload a new ssl certificate.  I'm guessing all would be Ok to keep using 19.5.2, as long as I can add new certificates. 

**Hardware:**
Arduino UNO
  BN: Arduino/Genuino Uno
  VID: 2A03
  PID: 0043
  SN: 95530343035351A04012

**Adafruit WINC1500 Breakout**
ATWINC1500-MR210PB

**Win10
**Arduino 1.8.5**
**Sketch - CheckWif101FirmwareVersion**** 

  WiFi101 firmware check.

  WiFi101 shield: DETECTED
    Firmware version installed: 19.5.2
    Latest firmware version available : 19.5.4

  **Check result: NOT PASSED**
    - The firmware version on the shield do not match the
      version required by the library, you may experience
      issues or failures.

**Sketch - FirmwareUpdater**
  Writing | ################################################## | 100% 1.62s
  avrdude: 10046 bytes of flash written
  avrdude: verifying flash memory against 
  ...
  avrdude: reading on-chip flash data:
  Reading | ################################################## | 100% 1.29s
  avrdude: verifying ...
  avrdude: 10046 bytes of flash verified
  avrdude done.  Thank you.

**WiFi101 Firmware Plug-in**
  COM7
  WINC1501 ModelB (19.5.4)
  Update Firmware
	java.lang.Exception: Error while erasing flash memory.
	at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.eraseFlash(FlasherSerialClient.java:139)
	at cc.arduino.plugins.wifi101.flashers.java.JavaFlasher.updateFirmware(JavaFlasher.java:79)
	at cc.arduino.plugins.wifi101.UpdaterImpl$3.run(UpdaterImpl.java:138)
  Update SSL Root Certificates
        java.lang.Exception: Error while reading flash memory.
	at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.readFlash(FlasherSerialClient.java:123)
	at cc.arduino.plugins.wifi101.flashers.java.JavaFlasher.uploadCertificates(JavaFlasher.java:127)
	at cc.arduino.plugins.wifi101.UpdaterImpl$4.run(UpdaterImpl.java:202)

**Comment by antellus** [comment]
Marking as duplicate, will post details in open issue.

**Comment by Clinerg59** [comment]
I'm looking to update my firmware for the WINC1501.  Has this issue be resolved and where do I get the latest firmware for this shield?
