### ISSUE TITLE
You updated the wifi provisioning html, how could I do that and compile a custom version of the firmware on my own?

### ISSUE THREAD

**Issue by grillinmuffins** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#17]
This would be incredibly helpful!!

**Comment by facchinm** [comment]
Hi @grillinmuffins ,
in fact we didn't compile the firmware :smile:  It is still closed source, but if you analyze the blob using a binary editor there is a section that contains the provisioning html page and resources (that you simply need to replace with your own).

**Comment by akash73** [comment]
closing this issue. 
Re-open if needed.

**Comment by joaomdmoura** [comment]
Hey @akash73, sorry for the dummy question, but how to I access the blob to update this? :)

**Comment by joaomdmoura** [comment]
I downloaded the project, updated the binary and built it locally.
But if I try to update the firmware it fails on the verification process, tried with both the .10.9 and master.
Any clues on why and how to get around it? Thanks in advance 😄

**Comment by joaomdmoura** [comment]
Was able to update the firmware inside the `Java/tools...` but it seems it fails if it get any bigger than its original size, so you can update the HTML as long you keep the same number of bytes. That worked for me.
Sorry for flooding the thread, just want to make sure other people can follow up similar steps in the future 😅
