### ISSUE TITLE
Latest firmware not available in Updater

### ISSUE THREAD

**Issue by mpfeil** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#18]
Hi everyone,

I am trying to update the firmware to the latest version (**19.5.4**). I saw the merged PR  #11 that it`s already merged.
Inside the Arduino IDE I just find Version **19.5.2**
![firmware_small](https://user-images.githubusercontent.com/2471172/40613994-13bf85f2-6281-11e8-8bd7-2de9bab44ff7.png)

I am running Arduino IDE 1.8.5 and WiFi101 library 0.15.2

Did I missed something to update?

Thank you for your help!

**Comment by facchinm** [comment]
Hi @mpfeil ,
the WiFi101 plugin is bundled with the IDE, and 1.8.5 was published before we updated to the new firmware. 
The tool is updated in both Hourly and Beta channels, and will be bundled in upcoming 1.8.6.
