### ISSUE TITLE
FirmwareUpdater tutorial missing sketch code tab

### ISSUE THREAD

**Issue by sandeepmistry** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#20]
@8bitkick was trying to use the code at the end of the [FirmwareUpdater tutorial](https://www.arduino.cc/en/Tutorial/FirmwareUpdater). However, it wouldn't compile.

The sketch in the WiFi101 library has two tabs: https://github.com/arduino-libraries/WiFi101/tree/master/examples/FirmwareUpdater - however the tutorial only show code for `FirmwareUpdater.ino` and **not** `Endianess.ino`.

Suggestions:

1) add another code snippet for the other tab
2) remove the code snippet entirely and guide people to use the example in the library, in the Java IDE and Create.

@simonepda

**Comment by SimonePDA** [comment]
The tutorial starts telling the user to use the WiFi101 examples -> FirmwareUpdater sketch, therefore it should be the preferred method.

Anyway I added the code for Endianess.ino to let the users see what's inside before loading the sketch.

**Comment by sandeepmistry** [comment]
@SimonePDA great! Thanks for updating.
