### ISSUE TITLE
Third party compatibility

### ISSUE THREAD

**Issue by awatterott** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#35]
Hi,

The latest updater plugin looks for the board name to show only compatible firmware versions. But this breaks the compatibility with boards from other manufacturers like our [BlueFly-Shield](https://learn.watterott.com/bluefly-shield/), Adafruit's [WINC1500 WiFi Shield](https://www.adafruit.com/product/3653) or [Feather M0 WiFi](https://www.adafruit.com/product/3010) (@ladyada).

I would suggest to add a checkbox to deactivate the automatic board identification or that all firmware versions are shown, when no compatible board is found.

Rgds,
Andreas

**Comment by facchinm** [comment]
Hi @awatterott ,
with version 0.10.5 (merged in hourly IDE two days ago via https://github.com/arduino/Arduino/commit/1b0f00ee38e4570dd7d559de7fe82055cb15fe6d ) there is no filter anymore on not-explicitly-compatible boards.
Can you test the latest hourly and report if it fixes the issue? Thanks!

**Comment by awatterott** [comment]
Hi Martino,
Thanks. Yes, it is working.
Sorry, I have missed the last commit.
