### ISSUE TITLE
Size of Wifi101 / WifiNINA firmware updater window too small

### ISSUE THREAD

**Issue by ghost** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#37]
When I open the Wifi101 / WifiNINA firmware updater window on a computer using windows 10 the window that opens is so small that I cannot see most of it.  Unfortunately I updated my certificates and now my WIFI rev 2 no longer runs the wifi server examples.  The examples used to run but now I get an error message saying it cannot talk to the wifi chip.  Can the window be recompiled so that we can resize it and be able to see the firmware update button?
-tim

**Comment by facchinm** [comment]
Fixed by merging #38
