### ISSUE TITLE
Support for Arduino CLI

### ISSUE THREAD

**Issue by stevenengland** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#60]
Hi everybody,

do you think it is possible to implement the firmware update flow/certificate loading flow in a way that it can be used with the help of a Arduino CLI instead of using the Arduino IDE?
I am working on a project to encourage non-technical people to support Public Science. For this, the technical barrier to entry must be as low as possible. Much lower than it is today with the help of the Arduino IDE. Therefore, I would like to offer the update process and the loading of the certificates automatically, for example via a script solution. Is something like this conceivable? The rest of my flow is already scripted (building the compileable-environment, compile and load to Arduino board). But I'm stuck with the WiFi shield :(

KR

**Comment by per1234** [comment]
Hi @stevenengland. There is a separate command line tool called "FirmwareUploader" that is designed specifically for this use case:
https://github.com/arduino/FirmwareUploader

It does leverage the Go packages of the Arduino CLI code base internally , but it is a completely standalone tool, so there is no need for the user to have Arduino CLI installed.

**Comment by stevenengland** [comment]
Hi @per1234 , that's great news! Thank you!
