### ISSUE TITLE
Please update to add new Arduino NINA-W102 firmware v1.4.6

### ISSUE THREAD

**Issue by khoih-prog** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#61]
Please update to add latest [Arduino NINA-W102 firmware v1.4.6](https://github.com/arduino/nina-fw/releases/tag/1.4.6)

**Comment by umbynos** [comment]
Done in https://github.com/arduino/arduino-fwuploader/pull/29 and [here](https://github.com/arduino/WiFi101-FirmwareUpdater-Plugin/commit/a307d1177e360af994c5eee08ef9a09a0017c8f2)
