### ISSUE TITLE
Select port select window need's a scroll bar

### ISSUE THREAD

**Issue by trlafleur** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#7]
OSX 10.12.2
IDE 1.8.1

![screen shot 2017-03-14 at 6 26 13 pm](https://cloud.githubusercontent.com/assets/4571691/23929515/0f53807e-08e4-11e7-9f94-e40f27ecbe2c.png)

**Comment by BallscrewBob** [comment]
+1 for this also under windows.

![scroll serial list](https://user-images.githubusercontent.com/8212730/46740544-19249a00-cc71-11e8-838e-28d75bab399b.jpg)

**Comment by facchinm** [comment]
Latest version (w/ NINA FW) has scrollbars enabled on serial port list, check it out in nightly IDE :wink:
